### ISSUE TITLE
Example for iuc10 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron-dev/NFDI4Ing_pyiron_base#1]
@srmnitc This example implements the workflow from [BAMresearch/NFDI4IngScientificWorkflowRequirements](https://github.com/BAMresearch/NFDI4IngScientificWorkflowRequirements) . This might also be relevant for the iuc10 in NFDI Matwerk.

**Comment by srmnitc** [comment]
I really like this, thanks a lot @jan-janssen. I think we should discuss with Tilmann in the next infra meeting or so, and think about opening a pull request.

**Comment by jan-janssen** [comment]
> I really like this, thanks a lot @jan-janssen. I think we should discuss with Tilmann in the next infra meeting or so, and think about opening a pull request.

I feel it still needs some more iterations, in particular as we have the distinction between job classes and job objects (instances) which is something the other frameworks like snakemake do not have, resulting in them having much shorter code. So let's discuss it tomorrow in the infrastructure meeting.
